name: cinemahub
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  http: ^1.6.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_dotenv: ^6.0.0
  get_it: ^9.2.0
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  google_fonts: ^6.3.3
  shimmer: ^3.0.0
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  youtube_explode_dart: ^3.0.5
  firebase_core: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/svg/
    - SECRET.env

  fonts:
    - family: SplineSans
      fonts:
        - asset: assets/fonts/spline_sans/SplineSans-Light.ttf
          weight: 300
        - asset: assets/fonts/spline_sans/SplineSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/spline_sans/SplineSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/spline_sans/SplineSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/spline_sans/SplineSans-Bold.ttf
          weight: 700

flutter_assets:
  assets_path:
    - assets/icons/svg/
  output_path: lib/core/resources
  filename: app_assets.dart
  ignore_comments: true
  ignore_prefix: true
  class_name: AppAssets
